### ISSUE TITLE
Find all the bugs in fixtureDMX class!

### ISSUE THREAD

**Issue by eliasjhojala** [eliasjhojala/DMX-lighting-controller#25]
It's really important to know does this class work properly or not.
The main reason why it wouldn't work is that it's not implemented everywhere properly.
If you find some bug please contact me! Thank you for help! :smile:

**Comment by ollpu** [comment]
Again, please note the branch the specified feature is in, especially if there is no sign of it in the Master branch.

**Comment by eliasjhojala** [comment]
It seems there are no bugs anymore
