### ISSUE TITLE
Exponential adjustion of fade

### ISSUE THREAD

**Issue by ollpu** [eliasjhojala/DMX-lighting-controller#31]
Currently, the Chases fade option has is quite hard to set on just the right speed. If you want a slow chase, the slowest speed is really not slow enough for many cases. If you want a fast chase, there are not much options (only around 10) to choose from and often it is very hard to move the slider so precisely. 
I'd suggest a formula of round(float(val)/25.5^4+1), so it would be easier to get a variety of faster speeds, and also possible to get a slower chase if needed.

**Comment by eliasjhojala** [comment]
Done
